spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/attus_bank
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
